shell zsh
background_opacity          0.95
window_padding_width        14
window_margin_width         0
window_border_width         1.5pt
confirm_os_window_close     0
allow_remote_control        yes
listen_on                   unix:/tmp/kitty

include themes/gruvbox.conf
