[theme]
background = "#18202b"
primary = "#d9f0ff"
secondary = "#9bb9cc"
title = "#9bdcff"
playing = "#b7e4f9"
playing_selected = "#ffffff"
playing_bg = "#30485a"
highlight = "#ffffff"
highlight_bg = "#426176"
error = "#ff8fa3"
error_bg = "#18202b"
statusbar = "#243242"
statusbar_progress = "#9bdcff"
statusbar_subtext = "#9bb9cc"
statusbar_text = "#d9f0ff"
statusbar_bg = "#243242"
cmdline = "#d9f0ff"
cmdline_bg = "#18202b"
search_match = "#9bdcff"
